Expansion of application period
Team-B1ND/dodamdodam-android pull request #143
Opened 2024-07-02 02:55 UTC by wnsgur1

## Overview (Required)

-  심자, 외출, 외박에서 월을 넘어 신청할 경우 날짜가 되돌아 오는 문제 해결
-  refresh를 추가하여 신청의 수락 여부를 확인 가능

## Screenshot

| Before | After |
| :--: | :--: |
| <img src="<img width="1470" alt="스크린샷 2024-07-02 오전 8 27 42" src="https://github.com/Team-B1ND/dodamdodam-android/assets/133772349/18f6567e-4d7f-4d1f-9d1d-5be5fe77c3af">" width="300" /> | <img src="<img width="1470" alt="스크린샷 2024-07-02 오전 8 27 50" src="https://github.com/Team-B1ND/dodamdodam-android/assets/133772349/13e631d1-16ca-4383-b8c6-7a756009650a">" width="300" /> |

## Issue

- close #142

2024-07-02 04:40 UTC, wsi1212 requested changes

2024-07-02 04:40 UTC, wsi1212 commented on gradle/libs.versions.toml
hotfix branch should push the patch version.

2024-07-06 15:10 UTC, SeokgyuYun approved these changes

2024-07-10 13:51 UTC, wsi1212 approved these changes

2024-07-15 00:07 UTC, merged