[Teacher/Register] Create Feature
Team-B1ND/dodamdodam-android pull request #167
Opened 2024-08-29 06:35 UTC by 8954sood

## Overview (Required)

- create a register feature
- ui module refactor to DDS v1.0.3
- fix not move textfield focus

## Screenshot
| Android | iOS |
| :--: | :--: |
| <img src="https://github.com/user-attachments/assets/60b65a33-22e8-4cce-add7-8d5a0608f46c" width="300" /> | <img src="https://github.com/user-attachments/assets/670e12fe-052e-4b4e-bdd3-07304e9a0da6" width="300" /> |

| Android | iOS |
| :--: | :--: |
| <img src="https://github.com/user-attachments/assets/dc36bf0a-a8ac-4f13-afef-a2823043f7d1" width="300" /> | <img src="https://github.com/user-attachments/assets/3230a1cf-42b0-4cea-8c49-2ca28fe740af" width="300" /> |

## Issue

- close #165

2024-08-29 11:24 UTC, wnsgur1 requested changes
수고하셨습니다.

2024-08-29 11:47 UTC, wnsgur1 reviewed
반영해주세요

2024-08-29 11:48 UTC, wnsgur1 commented on dodam-teacher-android/build.gradle.kts
> +            implementation(projects.common)
featureTeacher.registrer에 data.register와 network.register이 있을텐데 중복된거 같습니다

2024-08-29 11:48 UTC, wnsgur1 requested changes
반영해주세요

2024-08-29 11:48 UTC, wnsgur1 commented
> 반영해주세요

2024-08-29 11:51 UTC, 8954sood commented on dodam-teacher-android/build.gradle.kts
> +            implementation(projects.common)
혹시 api를 통해서 게속 내려오게 하는 방식이라면, 하면 안됩니다.
왜냐하면 은닉화에 가깝기 때문입니다.
나중에 참조 어디서 하고있는지 못찾는 문제점이 존재해요.

2024-08-29 11:52 UTC, wnsgur1 approved these changes

2024-08-29 17:44 UTC, wsi1212 approved these changes

2024-08-29 23:33 UTC, SeokgyuYun reviewed
하단 버튼이 너무 붙어있는 것 같아요 마진을 16dp 정도 주면 좋을것 같아요

2024-08-30 01:20 UTC, 8954sood commented
> 하단 버튼이 너무 붙어있는 것 같아요 마진을 16dp 정도 주면 좋을것 같아요

반영하였습니다.

2024-08-30 02:38 UTC, SeokgyuYun approved these changes

2024-08-30 02:54 UTC, merged