[Core] Notice View
Team-B1ND/dodamdodam-android pull request #268
Opened 2024-12-02 14:34 UTC by 8954sood

## Overview (Required)

- Create Notice View 
- Create Notice Create View
- Edit Meal Topbar and navigation

## Screenshot

| Notice | Notice Create |
| :--: | :--: |
| <img src="https://github.com/user-attachments/assets/9408c9aa-627c-41e7-a131-196d3ee0d32c" width="300" /> | <img src="https://github.com/user-attachments/assets/f8a40847-208e-4384-a7ae-2c9cd0ac4852" width="300" /> |
| Notice Create |
| <img src="https://github.com/user-attachments/assets/7d45af7a-f70d-4c8b-bffc-004770995e00" width="300" /> |

## Issue

- close #266

2024-12-03 00:18 UTC, wnsgur1 requested changes
수고하셨습니다.

2024-12-03 00:18 UTC, wnsgur1 commented on feature/notice/src/commonMain/kotlin/com/b1nd/dodam/notice/NoticeScreen.kt
> +                    )
아이콘 색이 label/alternative가 맞는지 확인해주세요

2024-12-03 00:18 UTC, wnsgur1 commented on feature/notice/src/commonMain/kotlin/com/b1nd/dodam/notice/NoticeScreen.kt
> +                        horizontalArrangement = Arrangement.spacedBy(8.dp),
vertical padding 20주세요

2024-12-04 13:03 UTC, 8954sood commented on feature/notice/src/commonMain/kotlin/com/b1nd/dodam/notice/NoticeScreen.kt
> +                    )
현재 기능이 구현되지 않아 임시로 disable 상태여서 색상이 labelAlternative로 보이지 않는 것입니다.

2024-12-09 01:36 UTC, wnsgur1 approved these changes

2024-12-09 01:37 UTC, merged