[Regisiter] Create regisiter screen
Team-B1ND/dodamdodam-android pull request #40
Opened 2024-02-26 21:35 UTC by wsi1212

## Overview (Required)

-  Create register screen

## Screenshot

 <img src="https://github.com/Team-B1ND/dodamdodam-android/assets/105199741/59a3a37e-a179-4a23-8ce3-15b670407310" width="300" />  <img src="https://github.com/Team-B1ND/dodamdodam-android/assets/105199741/cd5ce996-0a47-49ac-97ce-b8e76a057862" width="300" /> 

## Video

https://github.com/Team-B1ND/dodamdodam-android/assets/105199741/600614d5-acfc-4dd6-a3bd-b846c9c09b77

## ETC

- Performing login feature server error handling

## Issue

- close #28

2024-02-26 21:43 UTC, Mercen-Lee commented
PR Title is wrong

regisiter -> register

2024-02-26 21:56 UTC, Mercen-Lee requested changes
Change required

2024-02-26 21:56 UTC, Mercen-Lee commented on designsystem/src/main/java/com/b1nd/dodam/designsystem/util/PhoneVisualTransformation.kt
> +    override fun equals(other: Any?): Boolean {
Space missing between functions

2024-02-26 22:24 UTC, Mercen-Lee approved these changes
LGTM 👍

2024-02-27 18:29 UTC, merged

2024-03-08 05:24 UTC, Sanghyun0505 commented
LGBT 🏳️‍🌈