[Home] Create home screen
Team-B1ND/dodamdodam-android pull request #44
Opened 2024-03-13 10:01 UTC by SeokgyuYun

## Overview (Required)

- Create main screen with navhost
- Create home screen

## Screenshot

| Dark Mode | Light Mode |
| :--: | :--: |
<img src="https://github.com/Team-B1ND/dodamdodam-android/assets/100567149/4bde8ca3-aeca-4df7-88dd-4d77c5f77215" width="300" /> | <img src="https://github.com/Team-B1ND/dodamdodam-android/assets/100567149/522a744d-79b7-4c38-b71b-d4c20400e19d" width="300" /> |

https://github.com/Team-B1ND/dodamdodam-android/assets/100567149/44910f98-02a4-41b4-a004-f9195b45caf1

## Issue

- close #20

2024-03-13 12:52 UTC, wsi1212 requested changes
LGTM 👍

2024-03-13 12:52 UTC, wsi1212 commented on data/banner/src/main/AndroidManifest.xml
Please remove manifest

2024-03-13 12:52 UTC, wsi1212 commented on data/core/src/main/AndroidManifest.xml
Please remove manifest

2024-03-13 12:52 UTC, wsi1212 commented on data/night-study/src/main/AndroidManifest.xml
Please remove manifest

2024-03-13 12:52 UTC, wsi1212 commented on data/outing/src/main/AndroidManifest.xml
Please remove manifest

2024-03-13 12:52 UTC, wsi1212 commented on data/schedule/src/main/AndroidManifest.xml
Please remove manifest

2024-03-13 12:52 UTC, wsi1212 commented on data/schedule/src/main/java/com/b1nd/dodam/data/schedule/model/Grade.kt
idk why Grade have name param. If name param was't uesd, it'ld be better remove.

2024-03-13 12:52 UTC, wsi1212 commented on data/core/src/main/java/com/b1nd/dodam/data/core/model/Place.kt
idk why Place have name param. If name param was't uesd, it'ld be better remove.

2024-03-13 12:52 UTC, wsi1212 commented on data/wakeup-song/src/main/AndroidManifest.xml
Please remove manifest

2024-03-13 12:52 UTC, wsi1212 commented on dodam-student/src/main/AndroidManifest.xml
>      <uses-permission android:name="android.permission.INTERNET" />
Please remove duplicated permission

2024-03-13 12:52 UTC, wsi1212 commented on feature-student/home/src/main/java/com/b1nd/dodam/student/home/HomeScreen.kt
> +                                if (currentTime <= LocalTime.of(8, 10)) {
Please comment on each conditional of time

2024-03-13 12:52 UTC, wsi1212 commented on feature-student/home/src/main/java/com/b1nd/dodam/student/home/HomeScreen.kt
> +                                    if (tomorrow in latestSchedule.startDate..latestSchedule.endDate) {
Please write comment like line 1027

2024-03-13 12:52 UTC, wsi1212 commented on feature-student/home/src/main/java/com/b1nd/dodam/student/home/HomeScreen.kt
> +                                if (nextSchedule != null) {
Please write comment like line 1027

2024-03-13 12:52 UTC, wsi1212 commented on feature-student/main/src/main/AndroidManifest.xml
Please remove manifest

2024-03-13 12:52 UTC, wsi1212 commented on feature/login/src/main/java/com/b1nd/dodam/login/LoginScreen.kt
> +internal fun LoginScreen(viewModel: LoginViewModel = hiltViewModel(), onBackClick: () -> Unit, navigateToMain: () -> Unit) {
I think original is better then changed

2024-03-13 12:52 UTC, wsi1212 commented on network/banner/src/main/AndroidManifest.xml
Please remove manifest

2024-03-13 12:52 UTC, wsi1212 commented on network/core/src/main/java/com/b1nd/dodam/network/core/model/TokenResponse.kt
> -    @SerialName("token") val accessToken: String,
I think It'ld be better don't remove @SerialName

2024-03-13 12:52 UTC, wsi1212 commented on network/core/src/main/java/com/b1nd/dodam/network/core/model/TokenResponse.kt
> -    @SerialName("token") val accessToken: String,
It is same at network/login/model/LoginResponse and two classes are used same api, Isn't there a good way to combine the two classes into one?

2024-03-13 12:52 UTC, wsi1212 commented on network/meal/src/main/java/com/b1nd/dodam/network/meal/model/MealResponse.kt
> -    @SerialName("exists") val exists: Boolean,
I think it'ld be better at memorie to remove unused property exists

2024-03-13 12:52 UTC, wsi1212 commented on network/night-study/src/main/AndroidManifest.xml
Please remove manifest

2024-03-13 12:52 UTC, wsi1212 commented on network/night-study/src/test/java/com/b1nd/dodam/network/nightstudy/ExampleUnitTest.kt
Please write test code or delete this file

2024-03-13 12:52 UTC, wsi1212 commented on network/outing/src/main/AndroidManifest.xml
Please remove manifest

2024-03-13 12:52 UTC, wsi1212 commented on network/schedule/src/main/AndroidManifest.xml
Please remove manifest

2024-03-13 12:52 UTC, wsi1212 commented on network/wakeup-song/src/main/AndroidManifest.xml
Please remove manifest

2024-03-13 12:52 UTC, wsi1212 commented on network/wakeup-song/src/test/java/com/b1nd/dodam/wakeupsong/ExampleUnitTest.kt
Please write test code or remove file

2024-03-13 12:52 UTC, wsi1212 commented on settings.gradle.kts
> +include(":network:night-study")
please move these codes into list

2024-03-13 12:52 UTC, wsi1212 commented on ui-test-main/src/main/res/drawable/ic_launcher_background.xml
Please remove this file

2024-03-13 12:52 UTC, wsi1212 commented on ui-test-main/src/main/res/drawable/ic_launcher_foreground.xml
Please remove this file

2024-03-13 12:52 UTC, wsi1212 commented on ui-test-main/src/main/res/mipmap-anydpi/ic_launcher.xml
Please remove this file

2024-03-13 12:52 UTC, wsi1212 commented on ui-test-main/src/main/res/mipmap-anydpi/ic_launcher_round.xml
Please remove this file

2024-03-13 12:52 UTC, wsi1212 commented on ui-test-main/src/test/kotlin/com/b1nd/dodam/test/ExampleUnitTest.kt
Please write test code or remove this file

2024-03-14 08:41 UTC, SeokgyuYun commented on data/core/src/main/java/com/b1nd/dodam/data/core/model/Place.kt
name param will be used in schedule screen

2024-03-14 08:41 UTC, SeokgyuYun commented on data/schedule/src/main/java/com/b1nd/dodam/data/schedule/model/Grade.kt
grade param will be used in schedule screen

2024-03-14 09:01 UTC, SeokgyuYun commented on feature/login/src/main/java/com/b1nd/dodam/login/LoginScreen.kt
> +internal fun LoginScreen(viewModel: LoginViewModel = hiltViewModel(), onBackClick: () -> Unit, navigateToMain: () -> Unit) {
There's nothing I can do about it because ktlint changed

2024-03-14 09:04 UTC, SeokgyuYun commented on ui-test-main/src/main/res/drawable/ic_launcher_background.xml
It's impossible to remove the file because ui-test-main module is application module

2024-03-14 09:04 UTC, SeokgyuYun commented on ui-test-main/src/main/res/drawable/ic_launcher_foreground.xml
It's impossible to remove the file because ui-test-main module is application module

2024-03-14 09:04 UTC, SeokgyuYun commented on ui-test-main/src/main/res/mipmap-anydpi/ic_launcher_round.xml
It's impossible to remove the file because ui-test-main module is application module

2024-03-14 09:05 UTC, SeokgyuYun commented on ui-test-main/src/main/res/mipmap-anydpi/ic_launcher.xml
It's impossible to remove the file because ui-test-main module is application module

2024-03-14 10:23 UTC, wsi1212 approved these changes
LGTM 😘😘

2024-03-14 10:23 UTC, merged